/*DROP TRIGGERS*/

DROP TRIGGER accesorio_tri;
DROP TRIGGER categoria_tri;
DROP TRIGGER documento_tri;
DROP TRIGGER estado_tri;
DROP TRIGGER histInv_tri;
DROP TRIGGER marca_tri;
DROP TRIGGER modelo_tri;


/*DROP SECUENCIAS*/

DROP SEQUENCE accesorio_seq;
DROP SEQUENCE categoria_seq;
DROP SEQUENCE documento_seq;
DROP SEQUENCE estado_seq;
DROP SEQUENCE histInv_seq;
DROP SEQUENCE marca_seq;
DROP SEQUENCE modelo_seq;


/*DROP TABLAS*/

DROP TABLE DOCUMENTO;
DROP TABLE HISTORIALINVENTARIO;
DROP TABLE EQUIPO;
DROP TABLE ACCESORIO;
DROP TABLE ESTADO;
DROP TABLE CATEGORIA;
DROP TABLE MODELO;
DROP TABLE MARCA;
