/*DROP SECUENCIAS*/

DROP SEQUENCE accesorio_seq;
DROP SEQUENCE categoria_seq;
/*DROP SEQUENCE documento_seq;*/
DROP SEQUENCE estado_seq;
DROP SEQUENCE histInv_seq;
DROP SEQUENCE marca_seq;
DROP SEQUENCE modelo_seq;


/*DROP TABLAS*/

/*DROP TABLE DOCUMENTO;*/
DROP TABLE HISTORIALINVENTARIO;
DROP TABLE EQUIPO;
DROP TABLE ACCESORIO;
DROP TABLE ESTADO;
DROP TABLE CATEGORIA;
DROP TABLE MODELO;
DROP TABLE MARCA;
